"""선택형 backend 기반 프로젝트 메모리의 등록 정책과 artifact projection (패키지 파사드).

Asgard 메모리는 개인(로컬)과 프로젝트(선택 backend) 두 종류뿐이다. 이 패키지는 세 번째
정본을 만들지 않는다. 코드·문서·Git은 사실의 provenance이고, 활성 backend 하나가 팀 공유
프로젝트 메모리를 저장·검색한다.

모듈 구성 (구 단일 모듈 project_memory.py 의 분해 — 공개 표면은 여기서 그대로 재수출):
  records    — 상수·record dataclass·검증·직렬화 (순수 계층)
  scan       — 아티팩트 채굴: Git/worktree 스캔·구조 fingerprint·중요도 평가
  projection — manifest·kernel lock·plan/plan-id·backend sync
  retain     — turn retain·완료 제안 (stage/approve 승인 흐름 진입점)
"""

from ..memory import scan_threats
from ..memory_bridge import assert_backend_access, backend_target, server_retain_items, stage_retain
from .projection import (
    PROJECTION_LOCK_TTL,
    PROJECTION_MANIFEST,
    PROJECTION_VERSION,
    _artifact_document_id,
    _projection_guard,
    _projection_manifest_path,
    _projection_summary,
    _save_projection_manifest,
    _tombstone_item,
    _validate_projection_file,
    artifact_item,
    load_projection_manifest,
    projection_plan,
    projection_plan_id,
    sync_artifacts,
)
from .records import (
    _PLACEHOLDERS,
    _SECRET_PATTERNS,
    CONFIDENCE,
    IMPORTANCE,
    KINDS,
    MAX_ARTIFACT_BYTES,
    MAX_ONTOLOGY_VALUE,
    ONTOLOGY_SCHEMA,
    RELATIONS,
    STATUSES,
    ArtifactCandidate,
    CompletionProposalResult,
    ProjectRecord,
    TurnRetentionResult,
    ValidationResult,
    _neutral_line,
    record_item,
    render_record,
    scan_secrets,
    validate_record,
)
from .retain import _completion_kind, propose_completion, retain_turn
from .scan import (
    _IMPORTANT_CODE_WORDS,
    _MANIFESTS,
    _SECRET_NAMES,
    _SKIP_DIRS,
    _TEXT_EXTENSIONS,
    _argument_signature,
    _assess,
    _canonical_repo_path,
    _function_signature,
    _git_paths,
    _is_text_candidate,
    _node_signature,
    _python_signal,
    _structure,
    _walk_paths,
    changed_paths,
    scan_project,
    source_revision,
)

__all__ = [
    "CONFIDENCE",
    "IMPORTANCE",
    "KINDS",
    "MAX_ARTIFACT_BYTES",
    "MAX_ONTOLOGY_VALUE",
    "ONTOLOGY_SCHEMA",
    "PROJECTION_LOCK_TTL",
    "PROJECTION_MANIFEST",
    "PROJECTION_VERSION",
    "RELATIONS",
    "STATUSES",
    "ArtifactCandidate",
    "CompletionProposalResult",
    "ProjectRecord",
    "TurnRetentionResult",
    "ValidationResult",
    "_IMPORTANT_CODE_WORDS",
    "_MANIFESTS",
    "_PLACEHOLDERS",
    "_SECRET_NAMES",
    "_SECRET_PATTERNS",
    "_SKIP_DIRS",
    "_TEXT_EXTENSIONS",
    "_argument_signature",
    "_artifact_document_id",
    "_assess",
    "_canonical_repo_path",
    "_completion_kind",
    "_function_signature",
    "_git_paths",
    "_is_text_candidate",
    "_neutral_line",
    "_node_signature",
    "_projection_guard",
    "_projection_manifest_path",
    "_projection_summary",
    "_python_signal",
    "_save_projection_manifest",
    "_structure",
    "_tombstone_item",
    "_validate_projection_file",
    "_walk_paths",
    "artifact_item",
    "assert_backend_access",
    "backend_target",
    "changed_paths",
    "load_projection_manifest",
    "projection_plan",
    "projection_plan_id",
    "propose_completion",
    "record_item",
    "render_record",
    "retain_turn",
    "scan_project",
    "scan_secrets",
    "scan_threats",
    "server_retain_items",
    "source_revision",
    "stage_retain",
    "sync_artifacts",
    "validate_record",
]
