"""Asgard Studio의 정본 — 워크스페이스 하나에 팀·프로젝트·티켓.

  vocab.py     일을 세는 어휘 (상태 범주·우선순위·관계·건강도)
  db.py        `<에이전트 홈>/studio/workspace.db` 연결·스키마 (정본이라 손상돼도 안 지운다)
  teams.py     팀 — 번호의 주인, 워크플로 상태·사이클·트리아지의 단위
  projects.py  프로젝트·마일스톤·이니셔티브 — 팀을 가로지르는 축
  tickets.py   티켓의 규칙 — 상태·우선순위·라벨·주기·하위·차단·댓글·활동
  legacy.py    폴더마다 보드가 하나이던 시절의 저장소를 무손실로 들여오기

경계는 폴더가 아니라 워크스페이스다. 저장소 하나는 **팀 하나**로 들어오고(번호 `NOR-12`는
여전히 그 팀의 것), 프로젝트는 팀을 가로지른다. 폴더를 안 열고도 "지금 뭘 해야 하지"에
답할 수 있어야 하기 때문이다.

표면은 셋이 같은 것을 본다: 스튜디오 창(`/api/tickets*`) · `asgard ticket` · 에이전트의
`ticket` 툴. 저장소가 하나라 창에서 옮긴 칸이 CLI 에도 그대로 있고, 에이전트가 스스로 끊은
번호가 사람의 보드에 그대로 뜬다.
"""

from __future__ import annotations

from .db import StoreError, bind_path, db_path, exists, legacy_db_path, store_dir, workspace_path
from .projects import (
    ProjectError,
    add_milestone,
    add_project_team,
    add_update,
    archive_project,
    complete_milestone,
    create_initiative,
    create_project,
    delete_milestone,
    delete_project,
    get_initiative,
    get_project,
    list_initiatives,
    list_milestones,
    list_projects,
    list_updates,
    update_initiative,
    update_milestone,
    update_project,
)
from .teams import (
    TeamError,
    archive_team,
    bind_root,
    create_state,
    create_team,
    cycles_for,
    delete_state,
    get_team,
    list_states,
    list_teams,
    roll_cycle,
    unbind_root,
    update_state,
    update_team,
)
from .tickets import (
    TicketError,
    active_cycle,
    add_comment,
    board,
    close_cycle,
    create_cycle,
    create_label,
    create_ticket,
    delete_label,
    delete_ticket,
    find_ticket,
    get_ticket,
    link_tickets,
    list_cycles,
    list_labels,
    list_tickets,
    move_ticket,
    prefix,
    sort_key,
    summary,
    tickets_for_task,
    triage_accept,
    triage_decline,
    triage_queue,
    triage_snooze,
    unlink_tickets,
    update_ticket,
)
from .vocab import (
    HEALTH_LABEL,
    HEALTHS,
    INITIATIVE_STATUSES,
    LINK_KINDS,
    OPEN_STATUSES,
    PRIORITIES,
    PRIORITY_LABEL,
    PROJECT_STATUS_LABEL,
    PROJECT_STATUSES,
    SOURCES,
    STATUS_LABEL,
    STATUS_TYPE,
    STATUS_TYPES,
    STATUSES,
)

__all__ = [
    "HEALTHS",
    "HEALTH_LABEL",
    "INITIATIVE_STATUSES",
    "LINK_KINDS",
    "OPEN_STATUSES",
    "PRIORITIES",
    "PRIORITY_LABEL",
    "PROJECT_STATUSES",
    "PROJECT_STATUS_LABEL",
    "SOURCES",
    "STATUSES",
    "STATUS_LABEL",
    "STATUS_TYPE",
    "STATUS_TYPES",
    "ProjectError",
    "StoreError",
    "TeamError",
    "TicketError",
    "active_cycle",
    "add_comment",
    "add_milestone",
    "add_project_team",
    "add_update",
    "archive_project",
    "archive_team",
    "bind_path",
    "bind_root",
    "board",
    "close_cycle",
    "complete_milestone",
    "create_cycle",
    "create_initiative",
    "create_label",
    "create_project",
    "create_state",
    "create_team",
    "create_ticket",
    "cycles_for",
    "db_path",
    "delete_label",
    "delete_milestone",
    "delete_project",
    "delete_state",
    "delete_ticket",
    "exists",
    "find_ticket",
    "get_initiative",
    "get_project",
    "get_team",
    "get_ticket",
    "legacy_db_path",
    "link_tickets",
    "list_cycles",
    "list_initiatives",
    "list_labels",
    "list_milestones",
    "list_projects",
    "list_states",
    "list_teams",
    "list_tickets",
    "list_updates",
    "move_ticket",
    "prefix",
    "roll_cycle",
    "sort_key",
    "store_dir",
    "summary",
    "tickets_for_task",
    "triage_accept",
    "triage_decline",
    "triage_queue",
    "triage_snooze",
    "unbind_root",
    "unlink_tickets",
    "update_initiative",
    "update_milestone",
    "update_project",
    "update_state",
    "update_team",
    "update_ticket",
    "workspace_path",
]
